# Generated by Django 3.2.3 on 2021-12-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=32)),
                ('month', models.CharField(choices=[('coe', 'COE'), ('ece', 'ECE'), ('mech', 'Mech')], default='coe', max_length=9)),
            ],
        ),
    ]
