# Generated by Django 3.2.3 on 2021-12-09 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentAlumniInteraction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumni',
            old_name='month',
            new_name='branch',
        ),
    ]
