# Generated by Django 3.2.3 on 2021-12-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentAlumniInteraction', '0002_rename_month_alumni_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='l',
            field=models.TextField(max_length=200),
        ),
    ]
